### ISSUE TITLE
Filter by any payload property

### ISSUE THREAD

**Issue by bkeepers** [probot/webhooks#4]
I'd love to be able to filter by things like `repository.owner:probot` or `issue.number:5`

**Comment by JasonEtco** [comment]
I was thinking of implementing a GitHub-esque search filter, but that could get really difficult and cumbersome. I'd play around with having a number of inputs for the different properties. I **definitely** want search-by-repo, and I can see use-cases for better filtering for sure.

**Comment by JasonEtco** [comment]
closed by #6
